[workspace]
channels = ["conda-forge", "https://prefix.dev/skill-forge"]
platforms = ["linux-64", "osx-arm64", "win-64"]

[dependencies]
# Workaround for https://github.com/conda-forge/lerobot-feedstock/issues/1
rattler-build = "0.57.*"
conda-build = "*"
conda-smithy = "*"
agent-skill-conda-forge = "*"
agent-skill-rattler-build = "*"
gh = "*"
cf-job-logs = "*"

# Caching support
ccache = "*"
sccache = "*"

[activation.env]
# ccache support
CMAKE_C_COMPILER_LAUNCHER="sccache"
CMAKE_CXX_COMPILER_LAUNCHER="sccache"
